### ISSUE TITLE
Retarded `get_order_by_id(id)` 

### ISSUE THREAD

**Issue by seralekseenko** [b0noI/gemini-investor#12]
1. It can work or not work without any clear reason.

![Screenshot_20240724-194139.png](https://github.com/user-attachments/assets/f562d2df-5fd4-4368-bfe4-d51c4902a243)

![Screenshot_20240724-194201.png](https://github.com/user-attachments/assets/348c5abe-d337-4213-aed0-32602c9604a2)

2. Output is ugly.

**Comment by b0noI** [comment]
is this a blocker? I will ignore it for now

**Comment by seralekseenko** [comment]
![Screenshot_20240726-141703~2.png](https://github.com/user-attachments/assets/eef585ae-558d-4102-add6-d1e65f51969a)

**Comment by seralekseenko** [comment]
DUPLICATE
