### ISSUE TITLE
Improve doc for Gemini

### ISSUE THREAD

**Issue by seralekseenko** [b0noI/gemini-investor#13]
Clear explanations are needed for Gemini that Alpaca allows you to buy shares even in fractional parts.

For **buy/sell** functions: `buy_stock_by_market_price` and `sell_stock_by_market_price`.

I suggest adding the following text to the documentation: Alpaca allows you to buy shares in parts, not necessarily in whole parts. For example, you can **buy/sell** 0.5 or 1.8 shares.

**What it will give me:** I won't have to explain this Alpaca feature to the AI ​​every time.

**Comment by b0noI** [comment]
done
