### ISSUE TITLE
Invalid id request

### ISSUE THREAD

**Issue by seralekseenko** [b0noI/gemini-investor#14]
# get_order_by_id

The root of the problem is that for some reason the AI ​​stuffs client_order_id, not order_id, into this function.

**Comment by b0noI** [comment]
this is super strange, may I ask to:
* ask it in english
* post here the outcome

**Comment by seralekseenko** [comment]
![Screenshot_20240726-141703~2.png](https://github.com/user-attachments/assets/cb977340-805c-445c-85f3-58d43c2a9ecf)

**Comment by seralekseenko** [comment]
The problem was allocated!

When some order is created — the create* function returns the `client_order_id` and it is not the same as the `order_id`.

So, when I ask for info about some order —  I use the `client_order_id`, which was returned by create* function (sell/buy).

But the function `get_order_by_id` consumes the order id, not `client_order_id`.

Proofs in screenshots.

**Comment by b0noI** [comment]
ahhhhhhh, ty, going to fix it (just not tonight)

**Comment by b0noI** [comment]
correc it is now used everywhere
