### ISSUE TITLE
Need complicated stocks buy/sell functions.

### ISSUE THREAD

**Issue by seralekseenko** [b0noI/gemini-investor#17]
Base:

- [x] buy by limit price
- [x] sell by limit price
- [x] sell by stopLoss price
- [x] buy by limit or market AND create One Cancel Other order (limit sell + StopLoss sell)
- [ ] the same as above but with time limits (day order, 60 days, specified date)

**Comment by b0noI** [comment]
seel now requires limit and stop loss (exit strategy), you can not just set limit or stop losses, maybe next time

**Comment by b0noI** [comment]
you can also now buy and set exit strategy (separate messages)

**Comment by b0noI** [comment]
can you test and create sub-tasks/bugs if something is note htere

**Comment by seralekseenko** [comment]
One Cancel The other is currently still missing.

  I cannot create two orders for the same ticker separately.

  An exit strategy means:
  - if the limit is triggered, the stop loss is cancelled
  - if the stop-loss is triggered, the limit is cancelled.
