### ISSUE TITLE
Broken get_closed_orders_in_between_dates

### ISSUE THREAD

**Issue by seralekseenko** [b0noI/gemini-investor#18]
Sometimes work, some times do not work. :(

1.
![зображення](https://github.com/user-attachments/assets/6a12b157-39d1-45b8-81c5-a7eab314e8c3)

2.
![зображення](https://github.com/user-attachments/assets/8a287161-5b1b-43a1-9608-8bcf1f5b2d6d)

3. 
![зображення](https://github.com/user-attachments/assets/081a1558-d710-404b-8039-951870012a08)

4. No orders found → no problem )))
![зображення](https://github.com/user-attachments/assets/62148df3-9a10-437f-8d7c-2075512224b0)

**Comment by b0noI** [comment]
maybe (just maybe) it will work now :) can you try and reopen if still broken
