### ISSUE TITLE
Need upgrade for get_last_n_closed_orders

### ISSUE THREAD

**Issue by seralekseenko** [b0noI/gemini-investor#20]
- [ ]  Problem: I have to specify the exact ticker to search for a closed buy/sell option - it's incredibly inconvenient.

How it should be in my sick imagination: I write the query "give me the last 5 closed orders for the PLUG ticker" and I expect that it will show me orders for both shares and options that at least partially contain the PLUG ticker.
It is impossible to remember complete tickers for each individual option.

![зображення](https://github.com/user-attachments/assets/f9b3d7e4-1da2-4253-9abb-5fd3979bbdbb)

- [ ] Documentation improvements proposition

Actual is:

```py
   """Returns a string with the closed orders for the account.

    Args:
        limit (int): The maximum number of orders to return.
        ticker (str): The stock symbol to filter the orders.
    """
 ```
 
 I propose:
```py
   """Returns a string with the closed orders for the account.

    Args:
        limit (int): The maximum number of orders to return.
        ticker (str): The stock symbol or part of option symbol to filter the orders. This is an optional parameter.
    """
 ```

**Comment by b0noI** [comment]
should work now

**Comment by seralekseenko** [comment]
Я сповнений щастя від цієї функції! :)
