### ISSUE TITLE
Error submit_stocks_limit_buy_order

### ISSUE THREAD

**Issue by seralekseenko** [b0noI/gemini-investor#22]
{"error": "{\"code\":42210000,\"message\":\"fractional orders must be DAY orders\"}"}

![зображення](https://github.com/user-attachments/assets/c6b3324f-b229-4e2c-a882-6ac5837c37d6)

**Comment by b0noI** [comment]
not much I can do here dut to fractional shares, please use non-fractional shares for now

**Comment by seralekseenko** [comment]
When I try nonFractional — I'll report about the result.

**Comment by b0noI** [comment]
going to close, please reopen when you try non-fractional if it is still broken
