### ISSUE TITLE
get buying power functions priority

### ISSUE THREAD

**Issue by seralekseenko** [b0noI/gemini-investor#28]
We have two funct:
1. get_buying_power
2. get_non_marginable_buying_power

When I ask about buying power the first funct calls by default. But it will be more comfortable if the second funct will be called by default.

Because if we even have some margin — it is separated power and it should not be included in default buying power.

So, I propose:
- get_buying_power — returns power without margin, using by default.
- get_total_buying_power — returns power with margin

**Comment by b0noI** [comment]
since we do not have margin, I just removed one API and only left: return without margin
