### ISSUE TITLE
broken set_option_exit_strategy_by_option_ticker

### ISSUE THREAD

**Issue by seralekseenko** [b0noI/gemini-investor#33]
Serhii Oleksiienko, [05.08.24 19:37]
Тоді використай функцію set_option_exit_strategy_by_option_ticker для створення стратегії виходу:
- option_ticker: PDD240809C00130000
- qty: 5
- limit_price: 1.25
- stop_loss_price: 0.82

Jess, [05.08.24 19:37]
{"error": "'<' not supported between instances of 'str' and 'float'"}

![зображення](https://github.com/user-attachments/assets/c464f68a-5ac4-45a5-8fe2-2375675f7bec)

**Comment by b0noI** [comment]
BTW, VERY important thing, for OPTIONS this ONLY can set duration of the strategy - day

**Comment by b0noI** [comment]
might work now, give it a try and tell me if does not work still

**Comment by seralekseenko** [comment]
No chance

![зображення](https://github.com/user-attachments/assets/7ff8a3c2-e6ae-4106-8ec3-98017f2d9bab)

**Comment by b0noI** [comment]
methid now deleted, turins out that alpaca does NOT support complex orders for options, only limit sells and only DAY in force T_T
