### ISSUE TITLE
can't buy today's option

### ISSUE THREAD

**Issue by seralekseenko** [b0noI/gemini-investor#35]
Today is Aug-09-2024

![Screenshot_20240809-102934~2.png](https://github.com/user-attachments/assets/0b4c50c8-36a9-40d1-a53d-90c220dab8c1)

I cant realize day-trading strategy.
![зображення](https://github.com/user-attachments/assets/18f7a927-cc69-4d2c-9ad3-b0e526b8a62c)

**Comment by b0noI** [comment]
should be working now
