### ISSUE TITLE
broken "cancel_order_by_id"

### ISSUE THREAD

**Issue by seralekseenko** [b0noI/gemini-investor#36]
![зображення](https://github.com/user-attachments/assets/3b983b5f-603c-4161-baaf-0bd89dab6af9)

**Comment by seralekseenko** [comment]
I think this funct should return some result (err or Ok).

**Comment by b0noI** [comment]
I think this is how it should work for HELD orders, I guess

**Comment by b0noI** [comment]
closing since looks like it is working as expected, please reopne if u disagree or if this creates work related problems
