### ISSUE TITLE
magic buying power

### ISSUE THREAD

**Issue by seralekseenko** [b0noI/gemini-investor#37]
1. Somehow the buying power doesn't increase when I sold 1 option.
![Screenshot_20240814-080952~3.png](https://github.com/user-attachments/assets/34f1b9ba-d6e0-4b98-acf9-c3300164be48)

2. When I bot 11 options — the buying power doesn't change so much.

![Screenshot_20240814-080632~3.png](https://github.com/user-attachments/assets/df678ad3-4701-4cda-8874-ce679028e373)

**Comment by b0noI** [comment]
should be fixed now
