### ISSUE TITLE
Resolve `release_options(quantity, ticker, type, expiration_date, strike)

### ISSUE THREAD

**Issue by seralekseenko** [b0noI/gemini-investor#8]
It is not necessary now, but it will.

**Comment by b0noI** [comment]
release? exercise maybe?

**Comment by seralekseenko** [comment]
I mean exactly release, sell, not buy.

**Comment by b0noI** [comment]
ahhh, it called "sell to open", overall in options you have 4 actions:
* buy to open 
* buy to close
* sell to open
* sell to close

**Comment by b0noI** [comment]
<img width="724" alt="Screenshot 2024-08-14 at 8 32 12 PM" src="https://github.com/user-attachments/assets/37035617-1f2f-438a-91de-4069e30997a8">

this is what currently alpaca supports

**Comment by b0noI** [comment]
so, I have done minor updated, theoretically sell options by options symbol should now be able to "sell to open", I have not tested. But keep in mind only covered sells are supported!

going to close this bug for now, feel free to re-open later if it does not work
